apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = xxxxxxxx
    aws_secret_access_key = xxxxxxxxx
  config: |-
    [default]
    region = us-east-1

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
spec:
  description: >-
    This task performs operations on Amazon Web Services resources using aws.

  workspaces:
    - name: secrets
      optional: true
      mountPath: /tekton/home/.aws
  params:
    - name: SCRIPT
      description: The AWS script to run
      type: string
  steps:
    - name: awscli
      image: amazon/aws-cli
      script: "$(params.SCRIPT)"
      env:
        - name: AWS_CONFIG_FILE
          value: "$(workspaces.secrets.path)/config"
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: "$(workspaces.secrets.path)/credentials"

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: aws-run-
spec:
  taskRef:
    name: aws-cli
  params:
    - name: SCRIPT
      value: |
        aws sts get-caller-identity
  workspaces:
    - name: secrets
      secret:
        secretName: aws-credentials