apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: emit-result
spec:
  results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
  steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee $(results.current-date-unix-timestamp.path)

---

apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: print-result
spec:
  Params:
    - name: results
  steps:
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo -n "$(params.results)"

---

apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: results-pipeline
spec:
  tasks:
    - name: emit-result
      taskRef:
        name: emit-result
    - name: print-result
      taskRef:
        name: print-result
      params:
      - name: results
        value: $(tasks.emit-result.results.current-date-unix-timestamp)

---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: results-pipelinerun-
spec:
  pipelineRef:
    name: results-pipeline
